name: Sync Forked Repository

on:
  workflow_dispatch:
    inputs:
      source_repo_name:
        description: 'Source repo to get commit from (e.g., wtf911/ntfy)'
        required: true
      commit_sha:
        description: 'The full commit SHA to create the branch from'
        required: true
      destination_repo_name:
        description: 'Your fork to push the new branch to (e.g., YourUsername/ntfy)'
        required: true
      new_branch_name:
        description: 'The name for the new branch'
        required: true

jobs:
  create-branch-from-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.source_repo_name }}
          fetch-depth: 0 # Fetches all history to find the specific commit
          persist-credentials: false # Do not store credentials from checkout

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: Create and switch to new branch
        run: git checkout -b ${{ github.event.inputs.new_branch_name }} ${{ github.event.inputs.commit_sha }}

      - name: Add destination remote and push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.event.inputs.destination_repo_name }}.git
          git push origin ${{ github.event.inputs.new_branch_name }}
